getName/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^addName','addName.views.add_display',name="add_display"),
    url(r'^search','addName.views.search',name='search'),
    url(r'^','addName.views.search_form',name='search_form'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

addName/models.py
from django.db import models
from django import forms



# Create your models here.
class SignUp(models.Model):
	JIN="金"
	FEMALE='女'
	ADD_ATTR = (("金","金"),("木","木"),("水","水"),("火","火"),("土","土"))
	# ADD_ATTR = (('Gold',"金"),("Wood","木"),("Water","水"),("Fire","火"),("Earth","土"))
	ADD_GENDER = (('男','男'),("女","女"))
	ADD_LAN= (('中国','中国'),('其他','其他'))
	"""docstring for NewsLetter"""
	email = models.EmailField(blank=False)
	full_name = models.CharField(max_length = 120, blank=False, null=False,unique=True)
	country = models.CharField(max_length=6,choices=ADD_LAN)
	gender = models.CharField(max_length=6,choices=ADD_GENDER,default=FEMALE)
	attribute = models.CharField(max_length=6,choices=ADD_ATTR,default=JIN)
	timestamp = models.DateTimeField(auto_now_add = True, auto_now=False)
	updated = models.DateTimeField(auto_now_add = False, auto_now=True)
	

	def __unicode__(self): 
		return self.full_name

addName/forms.py
from django import forms
from .models import SignUp
from django.db import models

class SignUpForm(forms.ModelForm):
	class Meta:
		"""docstring for Meta"""
		model = SignUp
		fields = ['full_name','gender','attribute','country']
	# def clean_email(self):
	# 	email = self.cleaned_data.get('email')
	# 	email_base, provider = email.split("@")
	# 	domain,extention = provider.split(".")
	# 	if  not "usc" == domain:
	# 		raise forms.ValidationError("please use a valid usc domain")
	# 		return email
	# 	if not "edu"== extention:
	# 		raise forms.ValidationError("Please use a valid .EDU email address")
	# 	return email		
		
			

addName/views.py
from django.shortcuts import render
from .forms import SignUpForm
from django.conf import settings
from .models import SignUp
from django.template import RequestContext
from django.http import HttpResponse
from django.shortcuts import render_to_response
import random
from random import randint

# Create your views here.
# save data and display it on the page
def add_display(request):
    title = "已添加的名字："
    message=""
    signup = SignUp.objects.all()
    form = SignUpForm(request.POST or None)
    # if request.user.is_authenticated():
    #     title= "My Title is %s" %(request.user)
    context = {
        "entries" : signup,
        "template_title":title,
        "new_message":message,
        "form":form,
        
    } 

    if form.is_valid():
        instance=form.save(commit=False)
        full_name = form.cleaned_data.get("full_name")
        if instance.full_name == None:
            full_name = "New full_name"
        instance.full_name= full_name
        instance.save()
        message="new name added"
        context={
            "entries" : signup,
            "new_message":message,
            "form":form,
        }  

    return render(request, "addName.html", context)


# Get the request datas and show random one of them
def search(request):
  if ('country' in request.GET and request.GET['country']) and ('gender' in request.GET and request.GET['gender']) and('attr' in request.GET and request.GET['attr']):
    a = request.GET['country']
    b  = request.GET['gender']
    c  = request.GET['attr']
    query = a + " , " + b +" 以及 " + c
    results =SignUp.objects.filter(country__icontains=a, gender__icontains=b,attribute__icontains=c)
    count = results.count()
    single_result=results[randint(0,count-1)]
   
    return render_to_response('search_results.html',
      {'results': single_result ,  'query':query})
  else:
    return HttpResponse('Please submit a search term.')

def search_form(request):

  return render_to_response('search_form.html')

addName/templates/addName.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block addData %}
	<div class="container contentCenterize ">
		<div class ="row">
			<div class="col-3">
				<form action="" method="POST">{% csrf_token %}
					{{form|crispy}}
					<input class="btn btn-dark" type="SUBMIT" VALUE="Add New Name"></input>
					
				</form> 

			</div>
			<div class="col dataBackground dataStyle">
				<h1><b>Names:{{new_message}}</b></h1><br>
				<div class="row">
						<div class="col">	
							<label><b>金:</b></label>
								{% for item in entries %}
									{% if item.get_attribute_display == "金"%}
										<div>{{item.full_name}} {{item.get_gender_display}} {{item.get_attribute_display}}</div><br>
									{% endif %}
							    {% endfor%}
						</div>
						<div class="col">
							<label><b>木:</b></label>
								{% for item in entries %}
									{% if item.get_attribute_display == "木"%}
										
										<div>{{item.full_name}} {{item.get_gender_display}} {{item.get_attribute_display}}</div><br>
									{% endif %}
							    {% endfor%}
						</div>
						<div class="col">
							<label><b>水:</b></label>
								{% for item in entries %}
									{% if item.get_attribute_display == "水"%}
										
										<div>{{item.full_name}} {{item.get_gender_display}} {{item.get_attribute_display}}</div><br>
									{% endif %}
							    {% endfor%}
						</div>
						<div class="col">
							<label><b>火:</b></label>
								{% for item in entries %}
									{% if item.get_attribute_display == "火"%}
										
										<div>{{item.full_name}} {{item.get_gender_display}} {{item.get_attribute_display}}</div><br>
									{% endif %}
							    {% endfor%}
						</div>
						<div class="col">
							<label><b>土:</b></label>
								{% for item in entries %}
									{% if item.get_attribute_display == "土"%}
										<div>{{item.full_name}} {{item.get_gender_display}} {{item.get_attribute_display}}</div><br>
									{% endif %}
							    {% endfor%}
						</div>
						
				</div>		
				 <button class="btn btn-dark" style="position: fixed;bottom: 150px;" onclick="window.location.href='{% static "../.." %}'"> Landing Page</button>
			</div>
		</div>	
	</div>
{% endblock %}

addName/templates/base.html
{% include 'headerTemp.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{% block header %}

	{% endblock header%}
<title>You And Me</title>
</head>
<body style="">
	<div id="header">
		<p class="headerText">
			Get a name with specific element
		</p>
	</div>



{% block addData %}
{% endblock %}

{% block results %}
{% endblock %}

{% block response %}
{% endblock %}

</body>
<footer class="ifooter">
	<p>Posted by: JaNa</p>
	<p>Contact information: Belly-Berry</p>
</footer>


</html>

addName/templates/headerTemp.html
{% load staticfiles %}
{% block header %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'css/namer.css' %}">
	<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<link rel="stylesheet" href="{% static 'css/iconfont.css' %}" >
	<script src="{% static 'js/iconJs.js' %}"></script>
{% endblock %}

addName/templates/search_form.html
{% include 'headerTemp.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>

	{% block header %}
	{% endblock %}
<title>You And Me</title>
</head>
<body style="">
	<div id="header">
		<p class="headerText">
			Make your name with a specific element
		</p>
	</div>
	<div class="container contentCenterize">
		<form action="/search/" method="get">
			<div class="addBorder" id="countryLayer">  
				<p class="country">Language Of Your Name</p>
				<ul class="icon_lists">
					<li >
						<input type="radio" class="hide" name="country" id="china" value="中国"/>
						<label for="china" name ="country" class="icon iconfont icon-zhongguoditu"></label>
						<div class="name">中文名</div>
						<div class="englishSub">Chinese Name</div>

					</li>
					<li>
						<input type="radio" class="hide" name="country" id="others" value="其他"/>
						<label for="others"  class="icon iconfont icon-globle"></label>
						<div class="name">英文名</div>
						<div class="englishSub">English Name</div>
					</li>
				</ul>
			</div>
			<div class="addBorder" id="genderLayer">
				<div class="icon iconfont icon-xiangshang return-icon"></div>
				<p class="gender">Choose Your Gender</p>
				<ul class="icon_lists">
					<li>
						<input type="radio" class="hide" name="gender" id="boy" value="男"/>
						<label for="boy"  class="icon iconfont icon-boy"></label>
						<div class="name">正太</div>
						<div class="englishSub">Boy</div>
					</li>
					<li>
						<input type="radio" class="hide" name="gender" id="girl" value="女"/>
						<label for="girl"  class="icon iconfont icon-girl"></label>
						<div class="name">萝莉</div>
						<div class="englishSub">Girl</div>
					</li>
				</ul>
			</div>
			<div class="addBorder responsive" id="attLayer">
				<div id="secondReturn" class="icon iconfont icon-xiangshang return-icon"></div>
				<p class="country ">Select Your Element</p>
				<ul class="icon_lists">
					<li>
						<input type="radio" class="hide" name="attr" id="jin" value="金"/>
						<label for="jin"  class="icon attr iconfont icon-jin"></label>
						<!-- <i class="icon attr iconfont icon-jin"></i> -->
						<div class="name">Metal</div>

					</li>
					<li>
						<input type="radio" class="hide" name="attr" id="mu" value="木"/>
						<label for="mu"  class="icon attr iconfont icon-mu"></label>
						<!-- <i class="icon attr iconfont icon-jin"></i> -->
						<!-- <i class="icon attr iconfont icon-mu"></i> -->
						<div class="name">Wood</div>
					</li>
					<li>
						<input type="radio" class="hide" name="attr" id="shui" value="水"/>
						<label for="shui"  class="icon attr iconfont icon-shui"></label>
						<!-- <i class="icon attr iconfont icon-jin"></i> -->
						<div class="name">Water</div>
					</li>
					<li>
						<input type="radio" class="hide" name="attr" id="huo" value="火"/>
						<label for="huo"  class="icon attr iconfont icon-huo"></label>
						<!-- <i class="icon attr iconfont icon-huo"></i> -->
						<div class="name">Fire</div>
					</li>
					<li>
						<input type="radio" class="hide" name="attr" id="tu" value="土"/>
						<label for="tu"  class="icon attr iconfont icon-tu"></label>
						<div class="name">Earth</div>
					</li>
				</ul>
				<button class="btn btn-dark" type="submit" value="Search">Get My Name</button>
			</div>
		</form>
	</div>
	<footer class="ifooter">
		<p>Posted by: JarickAwhy</p>
		<p>Contact information: Belly || Berry</p>
	</footer>		
	</html>

addName/templates/search_results.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block results %}
<div class="container contentCenterize resultFormat">
    <button class="btn btn-dark"  onclick="window.location.href='{% static "../.." %}'"> Return</button>
    <div class="addBorder">
        <p>You searched for: <strong>{{query}}</strong></p>
        {% if results%}
        
         
             <label>Name：</label>{{ results.full_name}}&nbsp &nbsp&nbsp   
             <label>Gender：</label>{{ results.gender}}  &nbsp &nbsp&nbsp
             <label>Element：</label>{{ results.attribute}}&nbsp &nbsp&nbsp<br>
      
       {% else %}
       <p>sorry, the data you are searching is unavailable yet</p>
       {% endif %}
   </div>
</div>
{% endblock %}